[package]
name = "augustinus-tui"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
augustinus-app = { path = "../augustinus-app" }
crossterm = "0.29"
ratatui = "0.29"
unicode-width = "0.2"
